name: EterHome
version: '${version}'

main: fr.eternom.eterHome.Main
api-version: '26.2'
load: POSTWORLD
depend: [Vault]
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - redis.clients:jedis:6.2.0
  - com.mysql:mysql-connector-j:9.4.0
  - org.mariadb.jdbc:mariadb-java-client:3.5.6
  - org.postgresql:postgresql:42.7.8
  - org.xerial:sqlite-jdbc:3.50.3.0
  - com.h2database:h2:2.3.232
