package fr.eternom.eterHome.helper.sql;

import fr.eternom.eterHome.core.Sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * CRUD générique, qui récupère ses connexions auprès de {@link Sql}.
 * Les sous-classes n'adaptent que la syntaxe qui diffère d'une base à l'autre.
 */
public abstract class AbstractSql implements ISql {

    private static final Pattern IDENTIFIER = Pattern.compile("[a-z_][a-z0-9_]*");

    private final Sql sql;

    protected AbstractSql(Sql sql) {
        this.sql = sql;
    }

    protected char quote() {
        return '"';
    }

    protected String columnType(Column column) {
        return switch (column.getType()) {
            case INT -> "INT";
            case LONG -> "BIGINT";
            case DOUBLE -> "DOUBLE PRECISION";
            case BOOLEAN -> "BOOLEAN";
            case STRING -> "VARCHAR(" + column.getLength() + ")";
            case TEXT -> "TEXT";
            case UUID -> "CHAR(36)";
        };
    }

    protected String autoIncrementColumn(Column column) {
        return id(column.getName()) + " " + columnType(column) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    /** Upsert standard (PostgreSQL, SQLite). */
    protected String upsertSql(String table, List<String> columns, List<String> keys) {
        StringJoiner updates = new StringJoiner(", ");
        for (String column : columns) {
            if (!keys.contains(column)) {
                updates.add(column + " = EXCLUDED." + column);
            }
        }
        return insertSql(table, columns) + " ON CONFLICT (" + String.join(", ", keys) + ") "
                + (updates.length() == 0 ? "DO NOTHING" : "DO UPDATE SET " + updates);
    }

    @Override
    public void createTable(String table, Column... columns) {
        List<String> definitions = new ArrayList<>();
        List<String> primaryKeys = new ArrayList<>();

        for (Column column : columns) {
            if (column.isAutoIncrement()) {
                definitions.add(autoIncrementColumn(column));
                continue;
            }
            definitions.add(id(column.getName()) + " " + columnType(column)
                    + (column.isNotNull() || column.isPrimaryKey() ? " NOT NULL" : ""));
            if (column.isPrimaryKey()) {
                primaryKeys.add(id(column.getName()));
            }
        }
        if (!primaryKeys.isEmpty()) {
            definitions.add("PRIMARY KEY (" + String.join(", ", primaryKeys) + ")");
        }

        execute("CREATE TABLE IF NOT EXISTS " + id(table) + " (" + String.join(", ", definitions) + ")");
    }

    @Override
    public List<Row> get(String table, Map<String, ?> where) {
        List<Object> params = new ArrayList<>();
        return query("SELECT * FROM " + id(table) + where(where, params), params.toArray());
    }

    @Override
    public Optional<Row> getFirst(String table, Map<String, ?> where) {
        return get(table, where).stream().findFirst();
    }

    @Override
    public void insert(String table, Map<String, ?> values) {
        List<String> columns = new ArrayList<>();
        List<Object> params = new ArrayList<>();
        values.forEach((column, value) -> {
            columns.add(id(column));
            params.add(value);
        });
        execute(insertSql(table, columns), params.toArray());
    }

    @Override
    public void set(String table, Map<String, ?> values, String... keys) {
        if (keys.length == 0) {
            throw new IllegalArgumentException("set() nécessite au moins une colonne clé");
        }

        List<String> columns = new ArrayList<>();
        List<Object> params = new ArrayList<>();
        values.forEach((column, value) -> {
            columns.add(id(column));
            params.add(value);
        });

        List<String> keyColumns = Arrays.stream(keys).map(this::id).toList();
        if (!columns.containsAll(keyColumns)) {
            throw new IllegalArgumentException("Les clés " + keyColumns + " doivent faire partie des valeurs");
        }

        execute(upsertSql(table, columns, keyColumns), params.toArray());
    }

    @Override
    public int update(String table, Map<String, ?> values, Map<String, ?> where) {
        StringJoiner set = new StringJoiner(", ");
        List<Object> params = new ArrayList<>();
        values.forEach((column, value) -> {
            set.add(id(column) + " = ?");
            params.add(value);
        });
        return execute("UPDATE " + id(table) + " SET " + set + where(where, params), params.toArray());
    }

    @Override
    public int delete(String table, Map<String, ?> where) {
        List<Object> params = new ArrayList<>();
        return execute("DELETE FROM " + id(table) + where(where, params), params.toArray());
    }

    @Override
    public List<Row> query(String sql, Object... params) {
        try (Connection connection = this.sql.getConnection();
             PreparedStatement statement = prepare(connection, sql, params);
             ResultSet result = statement.executeQuery()) {

            ResultSetMetaData meta = result.getMetaData();
            List<Row> rows = new ArrayList<>();
            while (result.next()) {
                Map<String, Object> values = new HashMap<>();
                for (int i = 1; i <= meta.getColumnCount(); i++) {
                    values.put(meta.getColumnLabel(i).toLowerCase(Locale.ROOT), result.getObject(i));
                }
                rows.add(new Row(values));
            }
            return rows;
        } catch (SQLException e) {
            throw new IllegalStateException("Erreur SQL : " + sql, e);
        }
    }

    @Override
    public int execute(String sql, Object... params) {
        try (Connection connection = this.sql.getConnection();
             PreparedStatement statement = prepare(connection, sql, params)) {
            return statement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("Erreur SQL : " + sql, e);
        }
    }

    protected String insertSql(String table, List<String> columns) {
        return "INSERT INTO " + id(table) + " (" + String.join(", ", columns) + ") VALUES ("
                + String.join(", ", columns.stream().map(c -> "?").toList()) + ")";
    }

    /** Valide et entoure un nom de table/colonne ; empêche toute injection via les noms. */
    protected String id(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        if (!IDENTIFIER.matcher(lower).matches()) {
            throw new IllegalArgumentException("Nom de table/colonne invalide : " + name);
        }
        return quote() + lower + quote();
    }

    private String where(Map<String, ?> where, List<Object> params) {
        if (where == null || where.isEmpty()) {
            return "";
        }
        StringJoiner joiner = new StringJoiner(" AND ", " WHERE ", "");
        where.forEach((column, value) -> {
            if (value == null) {
                joiner.add(id(column) + " IS NULL");
            } else {
                joiner.add(id(column) + " = ?");
                params.add(value);
            }
        });
        return joiner.toString();
    }

    private PreparedStatement prepare(Connection connection, String sql, Object... params) throws SQLException {
        PreparedStatement statement = connection.prepareStatement(sql);
        try {
            for (int i = 0; i < params.length; i++) {
                Object value = switch (params[i]) {
                    case UUID uuid -> uuid.toString();
                    case Enum<?> e -> e.name();
                    case null, default -> params[i];
                };
                statement.setObject(i + 1, value);
            }
            return statement;
        } catch (SQLException e) {
            statement.close();
            throw e;
        }
    }
}
